# Generated by Django 2.2.3 on 2019-07-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='user_authentication.User')),
                ('followers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_authentication.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='followers',
            name='people',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='owner',
            new_name='commented_by',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='owner',
            new_name='liked_by',
        ),
        migrations.DeleteModel(
            name='followed',
        ),
        migrations.DeleteModel(
            name='followers',
        ),
    ]
