# Generated by Django 2.2.3 on 2019-07-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190723_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='owner',
            new_name='tweeted_by',
        ),
    ]
