# Generated by Django 2.2.3 on 2019-07-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190723_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='followed_by',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='user',
        ),
    ]
